<a href="https://colab.research.google.com/github/elshaymaAnalyst/PythonProject/blob/main/data_cleaning_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [270]:
import pandas as pd

In [271]:
df=pd.read_csv('/content/nba (1) (1).csv')

In [272]:
df.head(2)
# to see first row

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Bonus,Sales
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,06-Feb,180.0,Texas,7730337.0,NaN,NaN
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,06-Jun,235.0,Marquette,6796117.0,NaN,NaN

In [273]:
df.tail(3)
# to see last 3 row

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Bonus,Sales
454,Raul Neto,Utah Jazz,25.0,PG,24.0,06-Jan,179.0,NaN,900000.0,NaN,NaN
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,07-Mar,256.0,NaN,2900000.0,NaN,NaN
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0,NaN,NaN

In [274]:
df.columns
# to get the list of columns that avalable

Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
       'College', 'Salary', 'Bonus', 'Sales'],
      dtype='object')

In [275]:
df.shape
# number of row and columns
# (457,11)

(457, 11)

In [276]:
df.info()
#provide the information of df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 457 entries, 0 to 456
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      456 non-null    object
 1   Team      456 non-null    object
 2   Number    456 non-null    float64
 3   Position  456 non-null    object
 4   Age       456 non-null    float64
 5   Height    456 non-null    object
 6   Weight    456 non-null    float64
 7   College   372 non-null    object
 8   Salary    445 non-null    float64
 9   Bonus     0 non-null      float64
 10  Sales     0 non-null      float64
dtypes: float64(6), object(5)
memory usage: 39.4+ KB

In [277]:
df.isnull().sum()
# to provide the sum of null value

Name          1
Team          1
Number        1
Position      1
Age           1
Height        1
Weight        1
College      85
Salary       12
Bonus       457
Sales       457
dtype: int64

In [278]:
df.dropna(how='all',axis='columns')

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,06-Feb,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,06-Jun,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,06-May,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,06-May,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,06-Oct,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
452,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,06-Mar,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,06-Jan,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,07-Mar,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0

In [279]:
df=df.dropna(how='all',axis='columns')

In [280]:
df.shape

(457, 9)

In [281]:
df.head(2)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,06-Feb,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,06-Jun,235.0,Marquette,6796117.0

In [282]:
df=df.dropna(how='all',axis='rows')

In [283]:
df.shape

(456, 9)

In [284]:
df.isnull().sum()

Name         0
Team         0
Number       0
Position     0
Age          0
Height       0
Weight       0
College     84
Salary      11
dtype: int64

In [285]:
df['Salary'].mean()

np.float64(4848533.2831460675)

In [286]:
df['Salary'] = df['Salary'].fillna(4848533.2831460675)

In [287]:
df.isnull().sum()

Name         0
Team         0
Number       0
Position     0
Age          0
Height       0
Weight       0
College     84
Salary       0
dtype: int64

In [288]:
df.head(10)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,06-Feb,180.0,Texas,7.730337e+06
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,06-Jun,235.0,Marquette,6.796117e+06
2,John Holland,Boston Celtics,30.0,SG,27.0,06-May,205.0,Boston University,4.848533e+06
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,06-May,185.0,Georgia State,1.148640e+06
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,06-Oct,231.0,NaN,5.000000e+06
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,06-Sep,240.0,NaN,1.200000e+07
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,06-Aug,235.0,LSU,1.170960e+06
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2.165160e+06
8,Terry Rozier,Boston Celtics,12.0,PG,22.0,06-Feb,190.0,Louisville,1.824360e+06
9,Marcus Smart,Boston Celtics,36.0,PG,22.0,06-Apr,220.0,Oklahoma State,3.431040e+06

In [289]:
df.isnull().sum()

Name         0
Team         0
Number       0
Position     0
Age          0
Height       0
Weight       0
College     84
Salary       0
dtype: int64

In [290]:
df['College']=df['College'].fillna('Unknown')

In [291]:
df.isnull().sum()
#there is no null value now

Name        0
Team        0
Number      0
Position    0
Age         0
Height      0
Weight      0
College     0
Salary      0
dtype: int64

In [292]:
df.columns

Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
       'College', 'Salary'],
      dtype='object')

In [293]:
df=df.drop(['Height'],axis='columns')

In [294]:
df.shape

(456, 8)

In [295]:
df.shape[0]

456

In [296]:
df.head(2)

,Name,Team,Number,Position,Age,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,235.0,Marquette,6796117.0

In [297]:
df=df.drop(['Number'],axis='columns')

In [298]:
df.head(2)

            Name            Team Position   Age  Weight    College     Salary
0  Avery Bradley  Boston Celtics       PG  25.0   180.0      Texas  7730337.0
1    Jae Crowder  Boston Celtics       SF  25.0   235.0  Marquette  6796117.0

In [299]:
#selecting

In [300]:
df.columns

Index(['Name', 'Team', 'Position', 'Age', 'Weight', 'College', 'Salary'], dtype='object')

In [301]:
df['Age']

0      25.0
1      25.0
2      27.0
3      22.0
4      29.0
       ...
451    26.0
453    26.0
454    24.0
455    26.0
456    26.0
Name: Age, Length: 456, dtype: float64

In [302]:
df['Salary']

0      7.730337e+06
1      6.796117e+06
2      4.848533e+06
3      1.148640e+06
4      5.000000e+06
           ...
451    9.813480e+05
453    2.433333e+06
454    9.000000e+05
455    2.900000e+06
456    9.472760e+05
Name: Salary, Length: 456, dtype: float64

In [303]:
df[['Name', 'Team', 'Position']]

              Name            Team Position
0    Avery Bradley  Boston Celtics       PG
1      Jae Crowder  Boston Celtics       SF
2     John Holland  Boston Celtics       SG
3      R.J. Hunter  Boston Celtics       SG
4    Jonas Jerebko  Boston Celtics       PF
..             ...             ...      ...
451  Chris Johnson       Utah Jazz       SF
453   Shelvin Mack       Utah Jazz       PG
454      Raul Neto       Utah Jazz       PG
455   Tibor Pleiss       Utah Jazz        C
456    Jeff Withey       Utah Jazz        C

[456 rows x 3 columns]

In [304]:
df[['Position', 'Age','Weight']]

    Position   Age  Weight
0         PG  25.0   180.0
1         SF  25.0   235.0
2         SG  27.0   205.0
3         SG  22.0   185.0
4         PF  29.0   231.0
..       ...   ...     ...
451       SF  26.0   206.0
453       PG  26.0   203.0
454       PG  24.0   179.0
455        C  26.0   256.0
456        C  26.0   231.0

[456 rows x 3 columns]

In [305]:
df.columns

Index(['Name', 'Team', 'Position', 'Age', 'Weight', 'College', 'Salary'], dtype='object')

In [306]:
df[['Team','Age', 'Salary']]

               Team   Age        Salary
0    Boston Celtics  25.0  7.730337e+06
1    Boston Celtics  25.0  6.796117e+06
2    Boston Celtics  27.0  4.848533e+06
3    Boston Celtics  22.0  1.148640e+06
4    Boston Celtics  29.0  5.000000e+06
..              ...   ...           ...
451       Utah Jazz  26.0  9.813480e+05
453       Utah Jazz  26.0  2.433333e+06
454       Utah Jazz  24.0  9.000000e+05
455       Utah Jazz  26.0  2.900000e+06
456       Utah Jazz  26.0  9.472760e+05

[456 rows x 3 columns]

In [307]:
#Slicing

In [308]:
df.iloc[:,:]
# first:referes the row
#second:refers the column

,Name,Team,Position,Age,Weight,College,Salary
0,Avery Bradley,Boston Celtics,PG,25.0,180.0,Texas,7.730337e+06
1,Jae Crowder,Boston Celtics,SF,25.0,235.0,Marquette,6.796117e+06
2,John Holland,Boston Celtics,SG,27.0,205.0,Boston University,4.848533e+06
3,R.J. Hunter,Boston Celtics,SG,22.0,185.0,Georgia State,1.148640e+06
4,Jonas Jerebko,Boston Celtics,PF,29.0,231.0,Unknown,5.000000e+06
...,...,...,...,...,...,...,...
451,Chris Johnson,Utah Jazz,SF,26.0,206.0,Dayton,9.813480e+05
453,Shelvin Mack,Utah Jazz,PG,26.0,203.0,Butler,2.433333e+06
454,Raul Neto,Utah Jazz,PG,24.0,179.0,Unknown,9.000000e+05
455,Tibor Pleiss,Utah Jazz,C,26.0,256.0,Unknown,2.900000e+06
456,Jeff Withey,Utah Jazz,C,26.0,231.0,Kansas,9.472760e+05

In [309]:
df.iloc[0:3,:]

,Name,Team,Position,Age,Weight,College,Salary
0,Avery Bradley,Boston Celtics,PG,25.0,180.0,Texas,7.730337e+06
1,Jae Crowder,Boston Celtics,SF,25.0,235.0,Marquette,6.796117e+06
2,John Holland,Boston Celtics,SG,27.0,205.0,Boston University,4.848533e+06

In [313]:
df['College'].unique()
#provides unique values

array(['Texas', 'Marquette', 'Boston University', 'Georgia State',
       'Unknown', 'LSU', 'Gonzaga', 'Louisville', 'Oklahoma State',
       'Ohio State', 'Washington', 'Kentucky', 'North Carolina',
       'Arizona', 'Georgia Tech', 'Cincinnati', 'Miami (FL)', 'Stanford',
       'Syracuse', 'Saint Louis', 'Kansas', 'Georgetown', 'Texas A&M',
       'UCLA', 'UNLV', 'Wichita State', "Saint Joseph's", 'Notre Dame',
       'Norfolk State', 'Duke', 'Murray State', 'Tennessee State',
       'Bowling Green', 'Purdue', 'Wake Forest', 'Michigan', 'Missouri',
       'USC', 'Villanova', 'Rider', 'Utah', 'Belmont', 'Davidson',
       'Vanderbilt', 'Michigan State', 'Florida', 'Washington State',
       'Arizona State', 'Oklahoma', 'Wyoming', "St. John's", 'Maryland',
       'Wisconsin', 'Utah Valley', 'North Carolina State',
       'UC Santa Barbara', 'Baylor', 'Connecticut', 'Oregon State',
       'New Mexico', 'Oregon', 'Creighton', 'Arkansas', 'Memphis',
       "Saint Mary's", 'Tennessee', 'Alabama', 'Georgia', 'Colorado',
       'Boston College', 'Temple', 'Fresno State', 'IUPUI',
       'Eastern Washington', 'Western Michigan', 'Virginia',
       'Northeastern', 'Western Kentucky', 'Nevada', 'Illinois',
       'Kansas State', 'Charleston', 'Clemson', 'Blinn College',
       'Providence', 'Detroit', 'Rhode Island', 'California',
       'Cleveland State', 'Iowa State', 'Florida State',
       'Long Beach State', 'Penn State', 'Indiana', 'San Diego State',
       'Western Carolina', 'Houston', 'Xavier', 'Old Dominion',
       'Minnesota', 'Louisiana Tech', 'Bucknell', 'Pittsburgh',
       'Virginia Commonwealth', 'Harvard', 'Marshall', 'Iowa',
       'St. Bonaventure', 'Louisiana-Lafayette', 'Colorado State',
       'Virginia Tech', 'DePaul', 'Morehead State', 'Central Michigan',
       'Weber State', 'Lehigh', 'Westchester CC', 'Dayton', 'Butler'],
      dtype=object)

In [315]:
df['Team'].unique()
#how many unique

array(['Boston Celtics', 'Brooklyn Nets', 'New York Knicks',
       'Philadelphia 76ers', 'Toronto Raptors', 'Golden State Warriors',
       'Los Angeles Clippers', 'Los Angeles Lakers', 'Phoenix Suns',
       'Sacramento Kings', 'Chicago Bulls', 'Cleveland Cavaliers',
       'Detroit Pistons', 'Indiana Pacers', 'Milwaukee Bucks',
       'Dallas Mavericks', 'Houston Rockets', 'Memphis Grizzlies',
       'New Orleans Pelicans', 'San Antonio Spurs', 'Atlanta Hawks',
       'Charlotte Hornets', 'Miami Heat', 'Orlando Magic',
       'Washington Wizards', 'Denver Nuggets', 'Minnesota Timberwolves',
       'Oklahoma City Thunder', 'Portland Trail Blazers', 'Utah Jazz'],
      dtype=object)

In [316]:
df['College'].nunique()

119

In [317]:
df['College'].value_counts()
#Total count for each category

College
Unknown             84
Kentucky            21
Duke                20
Kansas              18
North Carolina      16
                    ..
Morehead State       1
Weber State          1
Central Michigan     1
Westchester CC       1
Lehigh               1
Name: count, Length: 119, dtype: int64

In [318]:
df.columns

Index(['Name', 'Team', 'Position', 'Age', 'Weight', 'College', 'Salary'], dtype='object')

In [319]:
#Sorting _ arranaging
#Name -ASC -A TO Z
#Name -Desc - Z TO A
#Salary - Asc-1 to 100
#Salary - Dec-100 to 1

In [322]:
df.sort_values(by='Name',ascending=True)

,Name,Team,Position,Age,Weight,College,Salary
152,Aaron Brooks,Chicago Bulls,PG,31.0,161.0,Oregon,2.250000e+06
356,Aaron Gordon,Orlando Magic,PF,20.0,220.0,Arizona,4.171680e+06
328,Aaron Harrison,Charlotte Hornets,SG,21.0,210.0,Kentucky,5.250930e+05
404,Adreian Payne,Minnesota Timberwolves,PF,25.0,237.0,Michigan State,1.938840e+06
312,Al Horford,Atlanta Hawks,C,30.0,245.0,Florida,1.200000e+07
...,...,...,...,...,...,...,...
386,Wilson Chandler,Denver Nuggets,SF,29.0,225.0,DePaul,1.044944e+07
270,Xavier Munford,Memphis Grizzlies,PG,24.0,180.0,Rhode Island,4.848533e+06
402,Zach LaVine,Minnesota Timberwolves,PG,21.0,189.0,UCLA,2.148360e+06
271,Zach Randolph,Memphis Grizzlies,PF,34.0,260.0,Michigan State,9.638555e+06
237,Zaza Pachulia,Dallas Mavericks,C,32.0,275.0,Unknown,5.200000e+06

In [323]:
df.columns

Index(['Name', 'Team', 'Position', 'Age', 'Weight', 'College', 'Salary'], dtype='object')

In [324]:
df.sort_values(by='Team',ascending=True)

,Name,Team,Position,Age,Weight,College,Salary
317,Lamar Patterson,Atlanta Hawks,SG,24.0,225.0,Pittsburgh,525093.0
309,Kent Bazemore,Atlanta Hawks,SF,26.0,201.0,Old Dominion,2000000.0
310,Tim Hardaway Jr.,Atlanta Hawks,SG,24.0,205.0,Michigan,1304520.0
311,Kirk Hinrich,Atlanta Hawks,SG,35.0,190.0,Kansas,2854940.0
312,Al Horford,Atlanta Hawks,C,30.0,245.0,Florida,12000000.0
...,...,...,...,...,...,...,...
371,Jarell Eddie,Washington Wizards,SG,24.0,218.0,Virginia Tech,561716.0
370,Jared Dudley,Washington Wizards,SF,30.0,225.0,Boston College,4375000.0
368,Alan Anderson,Washington Wizards,SG,33.0,220.0,Michigan State,4000000.0
382,John Wall,Washington Wizards,PG,25.0,195.0,Kentucky,15851950.0
369,Bradley Beal,Washington Wizards,SG,22.0,207.0,Florida,5694674.0

In [325]:
df.sort_values(by='Salary',ascending=True)

,Name,Team,Position,Age,Weight,College,Salary
32,Thanasis Antetokounmpo,New York Knicks,SF,23.0,205.0,Unknown,30888.0
130,Phil Pressey,Phoenix Suns,PG,25.0,175.0,Missouri,55722.0
291,Orlando Johnson,New Orleans Pelicans,SG,27.0,220.0,UC Santa Barbara,55722.0
135,Alan Williams,Phoenix Suns,C,23.0,260.0,UC Santa Barbara,83397.0
175,Jordan McRae,Cleveland Cavaliers,SG,25.0,179.0,Tennessee,111196.0
...,...,...,...,...,...,...,...
339,Chris Bosh,Miami Heat,PF,32.0,235.0,Georgia Tech,22192730.0
251,Dwight Howard,Houston Rockets,C,30.0,265.0,Unknown,22359364.0
33,Carmelo Anthony,New York Knicks,SF,32.0,240.0,Syracuse,22875000.0
169,LeBron James,Cleveland Cavaliers,SF,31.0,250.0,Unknown,22970500.0
109,Kobe Bryant,Los Angeles Lakers,SF,37.0,212.0,Unknown,25000000.0

In [326]:
df.sort_values(by='Name',ascending=False)

,Name,Team,Position,Age,Weight,College,Salary
237,Zaza Pachulia,Dallas Mavericks,C,32.0,275.0,Unknown,5.200000e+06
271,Zach Randolph,Memphis Grizzlies,PF,34.0,260.0,Michigan State,9.638555e+06
402,Zach LaVine,Minnesota Timberwolves,PG,21.0,189.0,UCLA,2.148360e+06
270,Xavier Munford,Memphis Grizzlies,PG,24.0,180.0,Rhode Island,4.848533e+06
386,Wilson Chandler,Denver Nuggets,SF,29.0,225.0,DePaul,1.044944e+07
...,...,...,...,...,...,...,...
312,Al Horford,Atlanta Hawks,C,30.0,245.0,Florida,1.200000e+07
404,Adreian Payne,Minnesota Timberwolves,PF,25.0,237.0,Michigan State,1.938840e+06
328,Aaron Harrison,Charlotte Hornets,SG,21.0,210.0,Kentucky,5.250930e+05
356,Aaron Gordon,Orlando Magic,PF,20.0,220.0,Arizona,4.171680e+06
152,Aaron Brooks,Chicago Bulls,PG,31.0,161.0,Oregon,2.250000e+06

In [327]:
df.sort_values(by='Team',ascending=False)

,Name,Team,Position,Age,Weight,College,Salary
369,Bradley Beal,Washington Wizards,SG,22.0,207.0,Florida,5694674.0
368,Alan Anderson,Washington Wizards,SG,33.0,220.0,Michigan State,4000000.0
381,Marcus Thornton,Washington Wizards,SF,29.0,205.0,LSU,200600.0
380,Garrett Temple,Washington Wizards,SG,30.0,195.0,LSU,1100602.0
379,Ramon Sessions,Washington Wizards,PG,30.0,190.0,Nevada,2170465.0
...,...,...,...,...,...,...,...
314,Kyle Korver,Atlanta Hawks,SG,35.0,212.0,Creighton,5746479.0
313,Kris Humphries,Atlanta Hawks,PF,31.0,235.0,Minnesota,1000000.0
312,Al Horford,Atlanta Hawks,C,30.0,245.0,Florida,12000000.0
311,Kirk Hinrich,Atlanta Hawks,SG,35.0,190.0,Kansas,2854940.0
310,Tim Hardaway Jr.,Atlanta Hawks,SG,24.0,205.0,Michigan,1304520.0

In [328]:
df.columns

Index(['Name', 'Team', 'Position', 'Age', 'Weight', 'College', 'Salary'], dtype='object')

In [329]:
#filter

In [330]:
df['Team'].unique()

array(['Boston Celtics', 'Brooklyn Nets', 'New York Knicks',
       'Philadelphia 76ers', 'Toronto Raptors', 'Golden State Warriors',
       'Los Angeles Clippers', 'Los Angeles Lakers', 'Phoenix Suns',
       'Sacramento Kings', 'Chicago Bulls', 'Cleveland Cavaliers',
       'Detroit Pistons', 'Indiana Pacers', 'Milwaukee Bucks',
       'Dallas Mavericks', 'Houston Rockets', 'Memphis Grizzlies',
       'New Orleans Pelicans', 'San Antonio Spurs', 'Atlanta Hawks',
       'Charlotte Hornets', 'Miami Heat', 'Orlando Magic',
       'Washington Wizards', 'Denver Nuggets', 'Minnesota Timberwolves',
       'Oklahoma City Thunder', 'Portland Trail Blazers', 'Utah Jazz'],
      dtype=object)

In [331]:
df[df['Team']=='Boston Celtics']

,Name,Team,Position,Age,Weight,College,Salary
0,Avery Bradley,Boston Celtics,PG,25.0,180.0,Texas,7.730337e+06
1,Jae Crowder,Boston Celtics,SF,25.0,235.0,Marquette,6.796117e+06
2,John Holland,Boston Celtics,SG,27.0,205.0,Boston University,4.848533e+06
3,R.J. Hunter,Boston Celtics,SG,22.0,185.0,Georgia State,1.148640e+06
4,Jonas Jerebko,Boston Celtics,PF,29.0,231.0,Unknown,5.000000e+06
5,Amir Johnson,Boston Celtics,PF,29.0,240.0,Unknown,1.200000e+07
6,Jordan Mickey,Boston Celtics,PF,21.0,235.0,LSU,1.170960e+06
7,Kelly Olynyk,Boston Celtics,C,25.0,238.0,Gonzaga,2.165160e+06
8,Terry Rozier,Boston Celtics,PG,22.0,190.0,Louisville,1.824360e+06
9,Marcus Smart,Boston Celtics,PG,22.0,220.0,Oklahoma State,3.431040e+06
10,Jared Sullinger,Boston Celtics,C,24.0,260.0,Ohio State,2.569260e+06
11,Isaiah Thomas,Boston Celtics,PG,27.0,185.0,Washington,6.912869e+06
12,Evan Turner,Boston Celtics,SG,27.0,220.0,Ohio State,3.425510e+06
13,James Young,Boston Celtics,SG,20.0,215.0,Kentucky,1.749840e+06
14,Tyler Zeller,Boston Celtics,C,26.0,253.0,North Carolina,2.616975e+06

In [332]:
df[df['Team']=='Brooklyn Nets']

,Name,Team,Position,Age,Weight,College,Salary
15,Bojan Bogdanovic,Brooklyn Nets,SG,27.0,216.0,Unknown,3425510.0
16,Markel Brown,Brooklyn Nets,SG,24.0,190.0,Oklahoma State,845059.0
17,Wayne Ellington,Brooklyn Nets,SG,28.0,200.0,North Carolina,1500000.0
18,Rondae Hollis-Jefferson,Brooklyn Nets,SG,21.0,220.0,Arizona,1335480.0
19,Jarrett Jack,Brooklyn Nets,PG,32.0,200.0,Georgia Tech,6300000.0
20,Sergey Karasev,Brooklyn Nets,SG,22.0,208.0,Unknown,1599840.0
21,Sean Kilpatrick,Brooklyn Nets,SG,26.0,219.0,Cincinnati,134215.0
22,Shane Larkin,Brooklyn Nets,PG,23.0,175.0,Miami (FL),1500000.0
23,Brook Lopez,Brooklyn Nets,C,28.0,275.0,Stanford,19689000.0
24,Chris McCullough,Brooklyn Nets,PF,21.0,200.0,Syracuse,1140240.0
25,Willie Reed,Brooklyn Nets,PF,26.0,220.0,Saint Louis,947276.0
26,Thomas Robinson,Brooklyn Nets,PF,25.0,237.0,Kansas,981348.0
27,Henry Sims,Brooklyn Nets,C,26.0,248.0,Georgetown,947276.0
28,Donald Sloan,Brooklyn Nets,PG,28.0,205.0,Texas A&M,947276.0
29,Thaddeus Young,Brooklyn Nets,PF,27.0,221.0,Georgia Tech,11235955.0

In [333]:
df['College'].unique()

array(['Texas', 'Marquette', 'Boston University', 'Georgia State',
       'Unknown', 'LSU', 'Gonzaga', 'Louisville', 'Oklahoma State',
       'Ohio State', 'Washington', 'Kentucky', 'North Carolina',
       'Arizona', 'Georgia Tech', 'Cincinnati', 'Miami (FL)', 'Stanford',
       'Syracuse', 'Saint Louis', 'Kansas', 'Georgetown', 'Texas A&M',
       'UCLA', 'UNLV', 'Wichita State', "Saint Joseph's", 'Notre Dame',
       'Norfolk State', 'Duke', 'Murray State', 'Tennessee State',
       'Bowling Green', 'Purdue', 'Wake Forest', 'Michigan', 'Missouri',
       'USC', 'Villanova', 'Rider', 'Utah', 'Belmont', 'Davidson',
       'Vanderbilt', 'Michigan State', 'Florida', 'Washington State',
       'Arizona State', 'Oklahoma', 'Wyoming', "St. John's", 'Maryland',
       'Wisconsin', 'Utah Valley', 'North Carolina State',
       'UC Santa Barbara', 'Baylor', 'Connecticut', 'Oregon State',
       'New Mexico', 'Oregon', 'Creighton', 'Arkansas', 'Memphis',
       "Saint Mary's", 'Tennessee', 'Alabama', 'Georgia', 'Colorado',
       'Boston College', 'Temple', 'Fresno State', 'IUPUI',
       'Eastern Washington', 'Western Michigan', 'Virginia',
       'Northeastern', 'Western Kentucky', 'Nevada', 'Illinois',
       'Kansas State', 'Charleston', 'Clemson', 'Blinn College',
       'Providence', 'Detroit', 'Rhode Island', 'California',
       'Cleveland State', 'Iowa State', 'Florida State',
       'Long Beach State', 'Penn State', 'Indiana', 'San Diego State',
       'Western Carolina', 'Houston', 'Xavier', 'Old Dominion',
       'Minnesota', 'Louisiana Tech', 'Bucknell', 'Pittsburgh',
       'Virginia Commonwealth', 'Harvard', 'Marshall', 'Iowa',
       'St. Bonaventure', 'Louisiana-Lafayette', 'Colorado State',
       'Virginia Tech', 'DePaul', 'Morehead State', 'Central Michigan',
       'Weber State', 'Lehigh', 'Westchester CC', 'Dayton', 'Butler'],
      dtype=object)

In [334]:
df[df['College']=='Texas']

,Name,Team,Position,Age,Weight,College,Salary
0,Avery Bradley,Boston Celtics,PG,25.0,180.0,Texas,7730337.0
66,Cory Joseph,Toronto Raptors,PG,24.0,190.0,Texas,7000000.0
133,P.J. Tucker,Phoenix Suns,SF,31.0,245.0,Texas,5500000.0
179,Tristan Thompson,Cleveland Cavaliers,C,25.0,238.0,Texas,14260870.0
208,Myles Turner,Indiana Pacers,PF,20.0,243.0,Texas,2357760.0
289,Jordan Hamilton,New Orleans Pelicans,SG,25.0,220.0,Texas,1015421.0
294,LaMarcus Aldridge,San Antonio Spurs,PF,30.0,240.0,Texas,19689000.0
384,D.J. Augustin,Denver Nuggets,PG,28.0,183.0,Texas,3000000.0
414,Kevin Durant,Oklahoma City Thunder,SF,27.0,240.0,Texas,20158622.0

In [335]:
df[df['College']=='Boston University']

,Name,Team,Position,Age,Weight,College,Salary
2,John Holland,Boston Celtics,SG,27.0,205.0,Boston University,4.848533e+06

In [336]:
df[df['Salary']>3000000]

,Name,Team,Position,Age,Weight,College,Salary
0,Avery Bradley,Boston Celtics,PG,25.0,180.0,Texas,7.730337e+06
1,Jae Crowder,Boston Celtics,SF,25.0,235.0,Marquette,6.796117e+06
2,John Holland,Boston Celtics,SG,27.0,205.0,Boston University,4.848533e+06
4,Jonas Jerebko,Boston Celtics,PF,29.0,231.0,Unknown,5.000000e+06
5,Amir Johnson,Boston Celtics,PF,29.0,240.0,Unknown,1.200000e+07
...,...,...,...,...,...,...,...
442,Trevor Booker,Utah Jazz,PF,28.0,228.0,Clemson,4.775000e+06
444,Alec Burks,Utah Jazz,SG,24.0,214.0,Colorado,9.463484e+06
445,Dante Exum,Utah Jazz,PG,20.0,190.0,Unknown,3.777720e+06
446,Derrick Favors,Utah Jazz,PF,24.0,265.0,Georgia Tech,1.200000e+07
448,Gordon Hayward,Utah Jazz,SF,26.0,226.0,Butler,1.540957e+07

In [337]:
df[df['Salary']>4000000]

,Name,Team,Position,Age,Weight,College,Salary
0,Avery Bradley,Boston Celtics,PG,25.0,180.0,Texas,7.730337e+06
1,Jae Crowder,Boston Celtics,SF,25.0,235.0,Marquette,6.796117e+06
2,John Holland,Boston Celtics,SG,27.0,205.0,Boston University,4.848533e+06
4,Jonas Jerebko,Boston Celtics,PF,29.0,231.0,Unknown,5.000000e+06
5,Amir Johnson,Boston Celtics,PF,29.0,240.0,Unknown,1.200000e+07
...,...,...,...,...,...,...,...
436,Damian Lillard,Portland Trail Blazers,PG,25.0,195.0,Weber State,4.236287e+06
442,Trevor Booker,Utah Jazz,PF,28.0,228.0,Clemson,4.775000e+06
444,Alec Burks,Utah Jazz,SG,24.0,214.0,Colorado,9.463484e+06
446,Derrick Favors,Utah Jazz,PF,24.0,265.0,Georgia Tech,1.200000e+07
448,Gordon Hayward,Utah Jazz,SF,26.0,226.0,Butler,1.540957e+07

In [340]:
df[(df['College']=='Texas') & (df['Salary']>3000000)]

,Name,Team,Position,Age,Weight,College,Salary
0,Avery Bradley,Boston Celtics,PG,25.0,180.0,Texas,7730337.0
66,Cory Joseph,Toronto Raptors,PG,24.0,190.0,Texas,7000000.0
133,P.J. Tucker,Phoenix Suns,SF,31.0,245.0,Texas,5500000.0
179,Tristan Thompson,Cleveland Cavaliers,C,25.0,238.0,Texas,14260870.0
294,LaMarcus Aldridge,San Antonio Spurs,PF,30.0,240.0,Texas,19689000.0
414,Kevin Durant,Oklahoma City Thunder,SF,27.0,240.0,Texas,20158622.0